name: Publish GitHub Packages
run-name: ${{ github.actor }} is testing out GitHub Packages 🚀
on: 
  push: 
    branches: 
       - master
    tags:
       - 'v[0-9]+.[0-9]+.[0-9]+'
  
jobs:          
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Get local.properties from secrets
        run: echo "${{secrets.LOCAL_PROPERTIES }}" > $GITHUB_WORKSPACE/local.properties
      - name: Publish to GitHub Packages
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish
